version: '3'

services:
  source_postgres:
    image: postgres:15.6
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  destination_postgres:
    image: postgres:15.6
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    
  elt_script:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

  dbt:
    build:
      # dockerfile: dbt-Dockerfile-simple
      dockerfile: dbt-Dockerfile-elementary
    ports:
      - "3000:8080"
      - "3001:8081"
    volumes:
      - ./custom_postgres:/dbt
      - ./dbt-profiles:/root
      #- ~/.dbt:/root
    depends_on:
      elt_script:
        condition: service_completed_successfully
    environment:
      DBT_PROFILE: custom_postgres
      DBT_TARGET: dev
    networks:
      - elt_network

networks:
  elt_network:
    driver: bridge