custom_postgres:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: host.docker.internal
      port: 5434
      user: postgres
      pass: secret
      dbname: destination_db
      schema: public
  target: dev


elementary:
  target: elementary
  outputs:
    elementary:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: secret
      port: 5434
      dbname: destination_db
      schema: public_elementary
      threads: 1