
version: 2

models:
  - name: films
    description: "This table contains details about films."
    columns:
      - name: film_id
        description: "Unique identifier for the film."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - custom_test_simple

      - name: release_date
        description: "Date the film was released."
        tests:
          - custom_test_for_year_check:
              max_year: 2024

      - name: user_rating
        description: "Rating that users gave the film."
        tests:
          - custom_test_for_user_rating_range_check:
              max_rating: 5.0
              min_rating: 3.0

  - name: film_ratings
    description: "This table maps films to the ratings and defines a rating category."
    columns:
      - name: film_id
        description: "Identifier for the film."
        tests:
          - dbt_expectations.expect_column_values_to_be_unique

      - name: title
        description: "Title of the film."
        tests:
          - relationships:
              to: ref('films')
              field:  title

      - name: rating_category
        description:  "Category of the rating"
        tests:
          - accepted_values:
              values:
                - Excellent
                - Good
                - Average
                - Poor
              tags: ["film_ratings_test_group"]

      - name: release_date
        description:  "Release date of the film."
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type:  date
          

      - name: user_rating
        description: "User rating of the film."
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2.0
              max_value: 5.0
          - custom_test_for_user_rating_range_check:
              max_rating: 4.5
              min_rating: 4.2
              tags: ["film_ratings_test_group"]